### ISSUE TITLE
RequestAuthorizationMiddleware config redirect url missing

### ISSUE THREAD

**Issue by wiifree** [cakephp/authorization#120]
I try to use to add the RequestAuthorizationMiddleware for some controller in my application in cake 4.
In the [Authorization Middleware](https://book.cakephp.org/authorization/2/en/middleware.html) i see a code block like this:

```php
$middlewareQueue->add(new AuthorizationMiddleware($this, [
    'unauthorizedHandler' => [
        'className' => 'Authorization.Redirect',
        'url' => '/users/login',
        'queryParam' => 'redirectUrl',
        'exceptions' => [
            MissingIdentityException::class,
            OtherException::class,
        ],
    ],
]));
```
I can add a redirect url if the authorization failed. 
This work fine but how i can add a redirect url for the [Request Authorization Middleware](https://book.cakephp.org/authorization/2/en/request-authorization-middleware.html) ?

**Comment by markstory** [comment]
The `RequestAuthorizationMiddleware` doesn't support redirect options at this time. It could be added in a future release. Would you like to help add that option?

**Comment by wiifree** [comment]
Yeah. I would like to help to implement this feature and maybe other features in future.

**Comment by othercorey** [comment]
Can't you just throw a `Authorization\Exception\Exception` which `AuthorizationMiddleware` will catch? You can re-use the `unauthorizedHandler` config for requests.

**Comment by matteorebeschi** [comment]
@othercorey that wouldn't work because, when throwing an exception in a RequestPolicy class (that is, a class that implements the RequestPolicyInterface interface), that exception needs to be caught in the RequestAuthorizationMiddleware, and not in the AuthorizationMiddleware.

In fact, the process method of AuthorizationMiddleware has a try/catch block, while the process method of RequestAuthorizationMiddleware doesn't.

I have opened a pull request to fix that.
Please let me know.
