### ISSUE TITLE
ORM Policy resolver broken

### ISSUE THREAD

**Issue by biermannm** [cakephp/authorization#156]
I have a couple of projects in which multidimensional data reside in some 4 to 10 main tables. The remaining tables in the projects are lookup tables that define the vocabulary. These tables should be viewable by every logged on user, but only be editable by administrators. Since I only have 2 sets of Authorization logic (except the users table, which is special), I only want to implement 2 policies and otherwise use the [ORM resolver](https://book.cakephp.org/authorization/2/en/policy-resolvers.html) to map my entities to just 2 policies. I developed under the latest CakePHP, which is 4.1, and the latest cakephp/auhorization, which is 2.0.5.

In the /src/Application.php I called the ORM resolver as specified in the cookbook:

```
public function getAuthorizationService(ServerRequestInterface $request): AuthorizationServiceInterface
    {
        $appNamespace = 'App'; // is the default
        $overrides = ['Confirmation' => 'Glossary',
                      'Institution' => 'Glossary',
                     ];
        $resolver = new OrmResolver($appNamespace, $overrides);
     }
```
However, this did not have the desired effect. Whenever I overrode the policy name, I got an error "Missing Policy Exception" from line 148 of ./vendor/cakephp/authorization/src/Policy/OrmResolver.php

Finally, I found the issue. Line 134 in ./vendor/cakephp/authorization/src/Policy/OrmResolver.php needs to be changed:

 ```
protected function findPolicy(string $class, string $name, string $namespace)
    {
        // $namespace = $this->getNamespace($namespace); // original statement, M. B.
        $name = $this->getNamespace($name); // correct statement, M. B.
        $policyClass = null;

       (...)

        if ($policyClass === null) {
            throw new MissingPolicyException([$class]);
        }

        return new $policyClass();
    }
```
The call to the protected function getNamespace needs to be made with the name of the entity (e.g. $name = 'Confirmation'), not with the appNameSpace (which is $namespace = 'App'). With this minor change in OrmResolver.php things work as they should.

**Comment by ndm2** [comment]
The resolver is correct, overrides are ment to override namespaces, not class/policy names. [**As shown in the docs**](https://book.cakephp.org/authorization/2/en/policy-resolvers.html#using-ormresolver), for example if you have a plugin with a base namespace of `Blog`, but you want to use the policy classes defined in the `Cms` plugin/namespace, then you'd do:

```php
$appNamespace = 'App';
$overrides = [
    'Blog' => 'Cms',
];
$resolver = new OrmResolver($appNamespace, $overrides);
```

which would cause the policy for `Blog\Model\Entity\Article` to be looked up as `Cms\Policy\ArticlePolicy` instead of `Blog\Policy\ArticlePolicy`.

The ORM resolver resolves class/policy names 1:1, ie `User` entity maps to `UserPolicy`, irrespective of the namespace. If you want to map a specific resource to a specific policy, then you need to use the `MapResolver`, eg:

```php
$resolver->map(Confirmation::class, GlossaryPolicy::class);
$resolver->map(Institution::class, GlossaryPolicy::class);
```

**Comment by biermannm** [comment]
Thanks a lot for the clarification including the sample code! 
I was surprised that I should have found a bug in CakePHP - I haven't in the last 10 years. I appreciate your patience and support.
